// Rendered control boundary: labels off, range/occlusion, typing, repeat, and
// actual use-vs-host routing, with no running world or GPU required.
import { strict as assert } from 'node:assert';
import { mock } from 'bun:test';
import { GlobalRegistrator } from '@happy-dom/global-registrator';
import * as THREE from 'three';
GlobalRegistrator.register({ url: 'https://renderer.example/' });
const base = `${import.meta.dir}/../client/lib/`;
const camera = new THREE.PerspectiveCamera(60, 1, 0.1, 100);
camera.position.set(0, 2, 5); camera.lookAt(0, 1, 0); camera.updateMatrixWorld();
let key: Function, occluded = false, hosted = true, overlay = false;
const uses: any[] = [], visits: any[] = [];
const myState = { pos: new THREE.Vector3(0, 0, 1) };
const state = { st: { entities: { lamp: { comp: { interaction: { action: 'toggle', label: 'Toggle lamp' } } } } } };
const entities = new Map([['lamp', new THREE.Group()]]);
let building = null;
mock.module(base+'realize/structure.js', () => ({ structureObject: () => building }));
mock.module(base+'core.js', () => ({ THREE, camera }));
mock.module(base+'base.js', () => ({ CONFIG: {}, bus: { on: (_: string, fn: Function) => { key = fn; } } }));
mock.module(base+'controller.js', () => ({ myState, photoMode: false }));
mock.module(base+'build.js', () => ({ isEditing: () => false }));
mock.module(base+'ui.js', () => ({ isOverlayOpen: () => overlay }));
mock.module(base+'state.js', () => ({ state }));
mock.module(base+'world.js', () => ({ entities }));
mock.module(base+'colliders.js', () => ({ raySegment: () => occluded ? 0.5 : null }));
mock.module(base+'net.js', () => ({ net: { joined: true }, sendVerb: (...args: any[]) => uses.push(args) }));
mock.module(base+'portosframe.js', () => ({ portosSession: () => hosted,
  frameRouteFor: (e: any) => e.comp.portos?.route, openInPortos: (...args: any[]) => visits.push(args) }));
const { tickInteraction } = await import('../client/lib/interaction.js');
const press = (repeat = false) => key({ code: 'KeyE', repeat, preventDefault() {} });
tickInteraction(100);
const button = document.querySelector<HTMLButtonElement>('.ew-interaction')!;
assert.equal(button.hidden, false);
assert.match(button.textContent!, /Toggle lamp/);
press(); press(true);
assert.deepEqual(uses, [['use', { id: 'lamp', action: 'toggle' }]]);
occluded = true; press(); tickInteraction(200); assert(button.hidden);
occluded = false;
myState.pos.z = 9; press(); tickInteraction(300); assert(button.hidden);
myState.pos.z = 1;
const input = document.createElement('input'); document.body.append(input); input.focus();
press(); tickInteraction(400); assert(button.hidden);
input.blur(); overlay = true; press(); overlay = false;
assert.equal(uses.length, 1);
state.st.entities.lamp = { comp: { portos: { action: 'visit', route: '/eidoverse' }, label: { name: 'Example pod' } } } as any;
entities.get('lamp')!.visible = false;
building = new THREE.Group();
tickInteraction(500); assert.match(button.textContent!, /Example pod/);
assert.equal(button.hidden, false, 'a visible native chamber remains usable with its model anchor hidden');
button.click();
assert.deepEqual(visits, [['lamp', '/eidoverse']]);
assert.equal(uses.length, 1, 'travel never sends a world verb');
hosted = false; tickInteraction(600); assert(button.hidden);
console.log('Interaction control checks passed');
