import {strict as a} from 'node:assert';
import {objectIdentity,readLabel,visibleLabels} from '../shared/label.js';
import {emptyState,foldEntry} from '../shared/fold.js';
const st=emptyState();
const emit=(verb,args)=>foldEntry(st,{verb,args,seq:1,ts:0,actor:'test'});
emit('spawn',{id:'thing',lib:'models/old_name.glb',pos:[0,0,0]});
emit('asset',{path:'models/old_name.glb',name:'Catalog name'});
a.equal(objectIdentity(st.entities.thing,st.assets).name,'Catalog name');
emit('comp',{id:'thing',type:'label',data:{name:'  🌍 <b>Hello</b>  ',description:'Details',visibility:'inspect'}});
a.equal(objectIdentity(st.entities.thing,st.assets).name,'🌍 <b>Hello</b>');
a.equal(objectIdentity(JSON.parse(JSON.stringify(st)).entities.thing,st.assets).name,'🌍 <b>Hello</b>');
emit('comp',{id:'thing',type:'label',data:null});
a.equal(objectIdentity(st.entities.thing,st.assets).name,'Catalog name');
a.equal(objectIdentity(st.entities.thing).name,'old name');
a.equal(readLabel({offset:[0,Infinity,0],name:32}).offset,null);
a.equal(readLabel({name:'🌍'.repeat(130)}).name.length,240);
a.equal(readLabel({visibility:'wat'}).visibility,'nearby');
const dense=Array.from({length:10000},(_,id)=>({id:String(id),authored:true,inView:true,distance:id/1000,visibility:'nearby'}));
a.equal(visibleLabels(dense,'nearby',null).length,32);
a.equal(visibleLabels(dense,'off',null).length,0);
a.equal(visibleLabels([{...dense[0],authored:false}],'all',null).length,0);
a.equal(visibleLabels([{...dense[0],visibility:'inspect'}],'nearby',null).length,0);
a.equal(visibleLabels(dense,'nearby','9999')[0].id,'9999');
console.log('label semantics, replay/removal and dense-world cap passed');
