// Real fold + real THREE transforms + actual DOM events; no GPU or live world.
// Regression: production folded entity values have no `id` property.
import { mock } from 'bun:test';
import { GlobalRegistrator } from '@happy-dom/global-registrator';
import { strict as assert } from 'node:assert';
import * as THREE from 'three';
GlobalRegistrator.register({ url: 'http://example.test/' });
const canvas = document.createElement('canvas');
canvas.getBoundingClientRect = () => ({ left: 0, top: 0, width: 390, height: 844 } as DOMRect);
Object.assign(globalThis, { innerWidth: 390, innerHeight: 844 });
const camera = new THREE.PerspectiveCamera(60, 390 / 844, 0.1, 100);
camera.position.set(0, 2, 8); camera.lookAt(0, 1, 0); camera.updateMatrixWorld();
const entities = new Map();
let rayCount = 0;
const base = `${import.meta.dir}/../client/lib/`;
mock.module(`${base}core.js`, () => ({ THREE, camera, renderer: { domElement: canvas } }));
mock.module(`${base}world.js`, () => ({ entities }));
mock.module(`${base}colliders.js`, () => ({ raySegment: () => { rayCount++; return null; } }));
mock.module(`${base}inspect.js`, () => ({ registerEditor: () => {} }));
const { CONFIG } = await import('../client/lib/base.js');
const { state, hydrate, foldLive } = await import('../client/lib/state.js');
const { emptyState, foldEntry } = await import('../shared/fold.js');
const { configureObjectLabels, initObjectLabels, tickObjectLabels } = await import('../client/lib/objectlabels.js');
const snapshot = emptyState();
let seq = 0;
const entry = (verb: string, args: object) => ({ verb, args, seq: ++seq, actor: 'fixture', ts: seq });
foldEntry(snapshot, entry('spawn', { id: 'landmark', lib: 'fixture.glb', pos: [0, 0, 0] }));
foldEntry(snapshot, entry('comp', { id: 'landmark', type: 'label', data: { name: 'Library', description: 'A quiet place to read.' } }));
assert.equal(snapshot.entities.landmark.id, undefined, 'fixture follows actual fold schema');
hydrate(snapshot);
const object = new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1), new THREE.MeshBasicMaterial());
entities.set('landmark', object);
assert.equal(CONFIG.objectLabels, 'off');
localStorage.setItem('ew-object-labels', 'all');
initObjectLabels(); tickObjectLabels(1000);
assert.equal(document.querySelector('.ew-object-labels'), null, 'standalone defaults off even with legacy preference');
configureObjectLabels({ mode: 'nearby' }); tickObjectLabels(1100);
const visible = () => [...document.querySelectorAll<HTMLButtonElement>('.ew-object-labels button')].filter(button => !button.hidden);
assert.equal(visible().length, 1, 'real folded entity resolves its rendered object');
assert.equal(visible()[0].textContent, 'Library');
assert.equal(visible()[0].dataset.entityId, 'landmark');
visible()[0].click();
const panel = document.querySelector<HTMLElement>('.ew-object-detail')!;
assert.equal(panel.hidden, false);
assert.match(panel.textContent!, /A quiet place to read/);
assert(!panel.textContent!.includes('fixture.glb'), 'ordinary details omit implementation paths');
const before = JSON.stringify(state.st);
const x = visible()[0].style.left;
object.position.x = 1;
tickObjectLabels(1200);
assert.notEqual(visible()[0].style.left, x, 'anchor follows live motion without a world write');
assert.equal(JSON.stringify(state.st), before);
// A real component update refreshes semantic identity without replacing the model.
foldLive(entry('comp', { id: 'landmark', type: 'label', data: { name: '<img src=x onerror=alert(1)>', description: 'Renamed' } }));
tickObjectLabels(1300);
assert.equal(panel.querySelector('img'), null);
assert.match(panel.textContent!, /Renamed/);
configureObjectLabels({ mode: 'off' }); tickObjectLabels(1400);
assert.equal(visible().length, 0);
assert.equal(panel.hidden, false, 'hiding floating labels keeps selected details usable');
const rays = rayCount; tickObjectLabels(1500); assert.equal(rayCount, rays, 'off does no spatial work');
configureObjectLabels({ mode: 'all' });
foldLive(entry('comp', { id: 'landmark', type: 'label', data: { name: 'Library', visibility: 'inspect' } }));
tickObjectLabels(1600); assert.equal(visible().length, 1);
for (let i = 0; i < 3; i++) { hydrate(state.st); configureObjectLabels({ mode: 'all' }); }
assert.equal(document.querySelectorAll('.ew-object-labels').length, 1);
assert.equal(document.querySelectorAll('.ew-object-labels button').length, 32);
foldLive(entry('remove', { id: 'landmark' })); tickObjectLabels(1700);
assert.equal(visible().length, 0); assert.equal(panel.hidden, true);
assert.equal(document.querySelector('select'), null, 'no detached object list or pick mode');
console.log('label DOM: real fold identity, default off, click details, motion, rename, removal, replay and no world writes passed');
GlobalRegistrator.unregister();
