// Actual receiver + label adapter with real fold and THREE, no GPU/live world.
// Configuration timing and stale-message guards use promises, never sleeps.
import { mock } from 'bun:test';
import { GlobalRegistrator } from '@happy-dom/global-registrator';
import { strict as assert } from 'node:assert';
import * as THREE from 'three';
GlobalRegistrator.register({ url: 'https://renderer.example/' });
const origin = 'https://host.example';
const sent: { data: any; origin: string }[] = [];
const host = { postMessage: (data: any, origin: string) => sent.push({ data, origin }) };
Object.defineProperty(window, 'parent', { value: host, configurable: true });
let answer: (value: Response) => void;
const originalFetch = globalThis.fetch;
globalThis.fetch = (() => new Promise(resolve => { answer = resolve; })) as typeof fetch;
const settle = async () => { for (let i = 0; i < 20; i++) await Promise.resolve(); };
const send = (data: any, from = host, sourceOrigin = origin) => window.dispatchEvent(new MessageEvent('message', {
  data, source: from as any, origin: sourceOrigin,
}));
const canvas = document.createElement('canvas');
canvas.getBoundingClientRect = () => ({ left: 0, top: 0, width: 390, height: 844 } as DOMRect);
Object.assign(globalThis, { innerWidth: 390, innerHeight: 844 });
const camera = new THREE.PerspectiveCamera(60, 390 / 844, .1, 100);
camera.position.set(0, 2, 8); camera.lookAt(0, 1, 0); camera.updateMatrixWorld();
const entities = new Map();
const base = `${import.meta.dir}/../client/lib/`;
mock.module(`${base}core.js`, () => ({ THREE, camera, renderer: { domElement: canvas } }));
mock.module(`${base}world.js`, () => ({ entities }));
mock.module(`${base}colliders.js`, () => ({ raySegment: () => null }));
mock.module(`${base}inspect.js`, () => ({ registerEditor: () => {} }));
const { state, hydrate, foldLive } = await import('../client/lib/state.js');
const { emptyState, foldEntry } = await import('../shared/fold.js');
const { initObjectLabels, tickObjectLabels } = await import('../client/lib/objectlabels.js');
let seq = 0;
const entry = (verb: string, args: object) => ({ verb, args, seq: ++seq, actor: 'fixture', ts: seq });
const st = emptyState();
foldEntry(st, entry('spawn', { id: 'landmark', lib: 'fixture.glb', pos: [0, 0, 0] }));
foldEntry(st, entry('comp', { id: 'landmark', type: 'label', data: { name: 'Example Goals', description: 'Shared plans', visibility: 'inspect' } }));
foldEntry(st, entry('comp', { id: 'landmark', type: 'portos', data: { route: '/goals/list' } }));
hydrate(st);
entities.set('landmark', new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1), new THREE.MeshBasicMaterial()));
initObjectLabels();
const visible = () => [...document.querySelectorAll<HTMLButtonElement>('.ew-object-labels button')].filter(button => !button.hidden);
const hello = { type: 'portos:connect', version: 1, nonce: 'one', labelVisibility: 'all-nearby' };
send(hello);
assert.equal(sent.length, 0, 'an early host claim is held until trusted config resolves');
assert.equal(visible().length, 0);
answer!(new Response(JSON.stringify({ parentOrigin: origin }), { status: 200 }));
await settle(); tickObjectLabels(1000);
assert.deepEqual(sent[0], { origin, data: { type: 'eidoverse:ready', version: 1, nonce: 'one', capabilities: { objectLabels: 1, portosNavigation: 1, labelPreferences: 1 } } });
assert.equal(visible().length, 1, 'late handshake enables the initially disabled renderer');
const unchanged = JSON.stringify(state.st);
visible()[0].click();
const open = () => [...document.querySelectorAll<HTMLButtonElement>('.ew-object-detail button')].find(button => button.textContent === 'Open in PortOS');
open()!.click();
assert.deepEqual(sent.at(-1), { origin, data: { type: 'eidoverse:navigate', version: 1, nonce: 'one', entityId: 'landmark', route: '/goals/list' } });
const pref = { type: 'portos:label-preference', version: 1, nonce: 'one', labelVisibility: 'off' };
send(pref, { postMessage: () => {} });
send(pref, host, 'https://other.example');
send({ ...pref, version: 2 }); send({ ...pref, nonce: 'stale' }); send({ ...pref, labelVisibility: 'everything' });
tickObjectLabels(1100); assert.equal(visible().length, 1, 'invalid messages cannot hide labels');
send(pref); tickObjectLabels(1200); assert.equal(visible().length, 0);
assert.equal(document.querySelector<HTMLElement>('.ew-object-detail')!.hidden, false);
assert(open(), 'selected navigation remains usable with labels off');
assert.equal(localStorage.getItem('ew-object-labels'), null, 'embed preferences never leak into framework storage');
send({ ...hello, nonce: 'two' }); tickObjectLabels(1300);
send(pref); tickObjectLabels(1400); assert.equal(visible().length, 1, 'replaced nonce cannot change the new session');
open()!.click(); assert.equal(sent.at(-1)!.data.nonce, 'two');
assert.equal(JSON.stringify(state.st), unchanged, 'inspection and frame preferences never mutate folded state');
foldLive(entry('comp', { id: 'landmark', type: 'portos', data: { route: '/eidoverse', action: 'visit' } }));
const teleport = [...document.querySelectorAll<HTMLButtonElement>('.ew-object-detail button')].find(button => button.textContent === 'Teleport as guest');
assert(teleport, 'a visitor chamber names the action it performs');
teleport.click();
assert.deepEqual(sent.at(-1)!.data, { type: 'eidoverse:navigate', version: 1, nonce: 'two', entityId: 'landmark', route: '/eidoverse' });
for (const route of ['https://other.example/', '/goals/list?query=1', '/goals/../apps']) {
  foldLive(entry('comp', { id: 'landmark', type: 'portos', data: { route } }));
  assert.equal(open(), undefined, 'malformed routes never offer navigation');
}
foldLive(entry('comp', { id: 'landmark', type: 'portos', data: { route: '/goals/list' } }));
assert(open());
send({ ...hello, nonce: null });
assert.equal(open(), undefined, 'invalid replacement retires the navigation session');
assert.equal(document.querySelectorAll('.ew-object-labels').length, 1);
console.log('frame DOM: delayed trust, real fold identity, label opt-in, navigation, invalid/stale messages, opt-out and session retirement passed');
globalThis.fetch = originalFetch;
GlobalRegistrator.unregister();
